export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "neutral-border": "#E2E8F0",
        "neutral-charcoal": "#212529",
        "neutral-surface": "#F8FAFC",
        "on-error": "#ffffff",
        "surface-container": "#eeedf7",
        "secondary-container": "#dde0e5",
        "on-tertiary-container": "#f1f5ff",
        "surface-tint": "#ba1a20",
        "background": "#fbf8ff",
        "outline-variant": "#e4beba",
        "on-primary": "#ffffff",
        "brand-red-hover": "#B71C1C",
        "on-primary-container": "#fff2f0",
        "traffic-yellow-border": "#FCD34D",
        "on-secondary-fixed-variant": "#43474c",
        "on-background": "#1a1b22",
        "primary-fixed": "#ffdad6",
        "error-container": "#ffdad6",
        "primary": "#af101a",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface": "#fbf8ff",
        "surface-container-highest": "#e3e1ec",
        "traffic-yellow": "#D97706",
        "secondary-fixed": "#e0e3e8",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-variant": "#e3e1ec",
        "secondary": "#5b5f63",
        "tertiary": "#49596e",
        "traffic-yellow-bg": "#FEF3C7",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d3e4fe",
        "traffic-green-bg": "#DCFCE7",
        "surface-container-low": "#f4f2fd",
        "on-secondary-container": "#5f6368",
        "inverse-surface": "#2f3038",
        "error": "#ba1a1a",
        "outline": "#8f6f6c",
        "surface-bright": "#fbf8ff",
        "on-primary-fixed-variant": "#930010",
        "on-secondary-fixed": "#181c20",
        "traffic-red-border": "#FCA5A5",
        "inverse-primary": "#ffb3ac",
        "neutral-slate-dark": "#333333",
        "traffic-green": "#16A34A",
        "surface-container-high": "#e8e7f1",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb3ac",
        "brand-red-subtle": "#FEF2F2",
        "on-surface-variant": "#5b403d",
        "inverse-on-surface": "#f1effa",
        "on-secondary": "#ffffff",
        "brand-red": "#D32F2F",
        "traffic-red-bg": "#FEE2E2",
        "on-tertiary-fixed": "#0b1c30",
        "traffic-red": "#EF4444",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#410003",
        "surface-dim": "#dad9e3",
        "traffic-green-border": "#86EFAC",
        "tertiary-container": "#617188",
        "secondary-fixed-dim": "#c3c7cc",
        "on-surface": "#1a1b22"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-lg": "1.5rem",
        "margin": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-sm": "0.5rem"
      },
      "fontFamily": {
        "headline-xl-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "code-num": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "headline": ["Inter"],
        "body": ["Inter"]
      },
      "fontSize": {
        "headline-xl-mobile": ["24px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "code-num": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }]
      }
    }
  }
}
